### ISSUE TITLE
[Bug]: python-agent运行时的bug

### ISSUE THREAD

**Issue by null-302** [HXSecurity/DongTai-agent-python#76]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/HXSecurity/DongTai/blob/main/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/HXSecurity/DongTai/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/HXSecurity/DongTai/issues/new/choose) without success.

### Version

1.1.2

### Installation Type

Official Docker Compose

### Service Name

DongTai-agent-python

flask，版本为1.1.2

### Describe the details of the bug and the steps to reproduce it

当在代码中使用eval("self.aData...")的时候InstallFcnHook无法识别aData（其中aData是变量），会报错：AttributeError: 'InstallFcnHook' object has no attribute 'aData'
![image](https://user-images.githubusercontent.com/44547827/143689627-66d5fe74-9d15-4f21-a28c-127dd0244be0.png)

**Comment by lostsnow** [comment]
fix by #64
